---
title: "Data Import"
output: github_document
---

This file is for doing data import.

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Import two datasets

Import our first dataset.

```{r}
litters_df = 
  read_csv(
    file = "data_import_examples/FAS_litters.csv",
    na = c("", "NA", ".")
    )

litters_df = janitor::clean_names(litters_df)
```

Import your second dataset.

```{r}
pups_df = 
  read_csv(
    file = "data_import_examples/FAS_pups.csv", 
    skip = 3,
    na = c("", "NA", ".")
    )

pups_df = janitor::clean_names(pups_df)
```


## Look at the data

```{r}
litters_df
pups_df
```

Head and tail

```{r}
head(litters_df, 20)

head(pups_df, 5)
```

Skimming??

```{r}
skimr::skim(pups_df)
```


## Oh Excel...

Jenny Bryan made `readxl` to solve our problems

```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

Look at the data!

```{r}
mlb_df
```

Load some LotR data.

Import FOTR words.

```{r}
fotr_df = 
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "B3:D6"
  )

fotr_df
```

What about Two Towers?

```{r}
tt_df = 
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "F3:H6"
  )

tt_df
```

## Import SAS

Read in the PULSE dataset

```{r}
pulse_df = 
  read_sas(
    "data_import_examples/public_pulse_data.sas7bdat"
  )

pulse_df = janitor::clean_names(pulse_df)
```


